[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
job_escrow = "27YquD9ZJvjLfELseqgawEMZq1mD1betBQZz5RgehNZr"

[programs.devnet]
job_escrow = "27YquD9ZJvjLfELseqgawEMZq1mD1betBQZz5RgehNZr"

[programs.mainnet]
job_escrow = "27YquD9ZJvjLfELseqgawEMZq1mD1betBQZz5RgehNZr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.moltcities/platform_wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 120000 tests/**/*.ts"
test-devnet = "USE_DEVNET=true yarn run ts-mocha -p ./tsconfig.json -t 120000 tests/**/*.ts"
